### PR TITLE
Added CentOS variant

### PR DESCRIPTION
**Pull request by dreybigney**

### CODE REVIEW

**Comment by bryanlatten** [comment]
@dreybigney hey there! thanks for your contribution. Any chance you could rebase to get this in?

**Comment by dreybigney** [comment]
@bryanlatten this has been rebased. Thanks!

**Comment by bryanlatten** [comment]
@dreybigney just needs to be added to `.travis.yml` in order to be part of the testing cycle. Then we can merge

**Comment by bryanlatten** [comment]
@dreybigney sorry, one last ask! can you update to `FROM behance/docker-base:2.3-centos`, it's building out right now. https://hub.docker.com/r/behance/docker-base/builds/

**Pull request merged**
