### PR TITLE
add secure http headers

### PR DESCRIPTION
**Pull request by ko-be**
Adding some secure http headers, as recommended by https://securityheaders.io/

Per https://github.com/bryanlatten/docker-php/pull/116#issuecomment-264217711 I am pushing up the changes here.

### CODE REVIEW

**Comment by markdunphy** [comment]
LGTM

**Comment by bryanlatten** [comment]
@ko-be any test we can make?

**Comment by ko-be** [comment]
@bryanlatten added some tests!

**Comment by remotelyliving** [comment]
👍

**Comment by aivtsan** [comment]
👍

**Comment by bryanlatten** [comment]
👍

**Pull request merged**
