### PR TITLE
Dockerfile: removed supervisor, added S6

### PR DESCRIPTION
**Pull request by bryanlatten**
S6 is *much* lighter than supervisor (1MB vs. 70MB, static compilation vs. python dependency) and supports cleaner startup processes, such as preemptive `cont-init.d` and `fix-attrs.d` script support. It also boots a container's process tree in under `100ms` (from their docs, but feels even faster in real life compared to supervisor). Supervisor (and runit) are not actually designed as PID 1 init replacements. 

- [x] nginx master process no longer run as root
- [x] permission issues for logging on stdout
- [x] permission issues for tmp folders
- [x] worker creation
- [x] 2-phase install support

### CODE REVIEW

**Comment by jimdelois** [comment]
This is bonkers!  (A good kind)

**Comment by jimdelois** [comment]
:white_check_mark:

**Comment by ko-be** [comment]
S6 looks like it's worth trying!

**Comment by ko-be** [comment]
:+1: but we should test this for a bit!

**Comment by mannytoledo** [comment]
:+1: I def need to learn more about what s6 is doing but this looks good.

**Comment by eadasiak** [comment]
:+1: This is really great -- a muuuuch better fit for containers than runit/supervisord.

**Pull request merged**
